/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import control.C45;
import control.ConfusionMatrix;
import control.ExcelHandler;
import control.PSO;
import entity.Particle;
import control.Reflector;
import control.SplitValidator;
import entity.Data;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author acer
 */
public class App extends javax.swing.JFrame {
    
    private List<entity.Data> data = new ArrayList<>();
    private boolean analyzed = false;
    private C45 trainedC45 = null;
    private C45 trainedPSOC45 = null;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dashboard = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        tittle_data = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tabel_data = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nutritionalStatusTable = new javax.swing.JTable();
        buton_data = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        analysis = new javax.swing.JPanel();
        splitRatioTextField = new javax.swing.JTextField();
        numPopulationTextField = new javax.swing.JTextField();
        numIterationTextField = new javax.swing.JTextField();
        c1TextField = new javax.swing.JTextField();
        c2TextField = new javax.swing.JTextField();
        targetTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        analyzeButton = new javax.swing.JButton();
        Hasil1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        accuracyTable = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cm_C45 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        cm_PSOC45 = new javax.swing.JTable();
        hasilText = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        classifyButton = new javax.swing.JButton();
        lantaiTextField = new javax.swing.JTextField();
        kelembabanTextField = new javax.swing.JTextField();
        pencahayaanTextField = new javax.swing.JTextField();
        ventilasiTextField = new javax.swing.JTextField();
        ptrTextField = new javax.swing.JTextField();
        penghasilanTextField = new javax.swing.JTextField();
        pekerjaanTextField = new javax.swing.JTextField();
        pendidikanTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        dindingTextField = new javax.swing.JTextField();
        atapTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        classifiedLabelText = new javax.swing.JLabel();
        classification = new javax.swing.JPanel();
        hasilText1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        classifyButton1 = new javax.swing.JButton();
        namaTextField1 = new javax.swing.JTextField();
        classifiedLabelText1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(723, 850));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1879, 1100));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setText("Optimasi C4.5");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText(".");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText(".");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel6.setText("dengan PSO");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(525, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", home);

        dashboard.setLayout(new javax.swing.BoxLayout(dashboard, javax.swing.BoxLayout.LINE_AXIS));

        Data.setLayout(new javax.swing.BoxLayout(Data, javax.swing.BoxLayout.PAGE_AXIS));

        tittle_data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tittle_data.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Data Pasien Penyakit Ispa");

        jButton3.setText("Analyze");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tittle_dataLayout = new javax.swing.GroupLayout(tittle_data);
        tittle_data.setLayout(tittle_dataLayout);
        tittle_dataLayout.setHorizontalGroup(
            tittle_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tittle_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tittle_dataLayout.setVerticalGroup(
            tittle_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tittle_dataLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(tittle_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Data.add(tittle_data);

        tabel_data.setPreferredSize(new java.awt.Dimension(700, 70));
        tabel_data.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(471, 500));

        nutritionalStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Pendidikan", "Pekerjaan", "Penghasilan", "Ptr", "Ventilasi", "Pencahayaan", "Kelembaban", "Lantai", "Dinding", "Atap", "Ispa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nutritionalStatusTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(nutritionalStatusTable);

        tabel_data.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        buton_data.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        buton_data.setPreferredSize(new java.awt.Dimension(211, 20));
        buton_data.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Muat Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadData(evt);
            }
        });
        buton_data.add(jButton1, java.awt.BorderLayout.PAGE_START);

        tabel_data.add(buton_data, java.awt.BorderLayout.CENTER);

        Data.add(tabel_data);

        dashboard.add(Data);

        jTabbedPane1.addTab("Dashboard", dashboard);

        analysis.setPreferredSize(new java.awt.Dimension(1874, 1000));

        splitRatioTextField.setText("0.7");

        numPopulationTextField.setText("20");

        numIterationTextField.setText("10");

        c1TextField.setText("0.91");

        c2TextField.setText("0.09");

        targetTextField.setText("0.9");

        jLabel9.setText("Split Ratio");

        jLabel11.setText("Num. Population");

        jLabel12.setText("Num. Iteration");

        jLabel13.setText("C1");

        jLabel14.setText("C2");

        jLabel15.setText("Target");

        analyzeButton.setText("Analyze");
        analyzeButton.setPreferredSize(null);
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });

        Hasil1.setBackground(new java.awt.Color(0, 0, 204));
        Hasil1.setPreferredSize(new java.awt.Dimension(50, 541));
        Hasil1.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setText("Hasil Akurasi");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(390, 34));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setPreferredSize(new java.awt.Dimension(452, 34));

        accuracyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "C4.5", "PSO - C4.5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accuracyTable.setPreferredSize(new java.awt.Dimension(150, 32));
        jScrollPane6.setViewportView(accuracyTable);

        jPanel12.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel13.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Confusion Matrix C4.5");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(390, 90));
        jPanel14.setLayout(new java.awt.BorderLayout());

        cm_C45.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null},
                {"2", null, null}
            },
            new String [] {
                "", "1", "2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cm_C45.setName(""); // NOI18N
        jScrollPane7.setViewportView(cm_C45);

        jPanel14.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel15.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Confusion Matrix PSO - C4.5");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.add(jPanel15);

        jPanel16.setPreferredSize(new java.awt.Dimension(390, 90));
        jPanel16.setLayout(new java.awt.BorderLayout());

        cm_PSOC45.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null},
                {"2", null, null}
            },
            new String [] {
                "", "1", "2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(cm_PSOC45);

        jPanel16.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel16);

        Hasil1.add(jPanel10, java.awt.BorderLayout.CENTER);

        jLabel16.setText("Nama");

        classifyButton.setText("Classify");
        classifyButton.setPreferredSize(null);
        classifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classifyButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Pendidikan");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel20.setText("Pekerjaan");

        jLabel22.setText("Penghasilan");

        jLabel23.setText("PTR");

        jLabel24.setText("Ventilasi");

        jLabel25.setText("Pencahayaan");

        jLabel26.setText("Kelembaban");

        jLabel27.setText("Lantai");

        jLabel28.setText("Dinding");

        jLabel29.setText("Atap");

        classifiedLabelText.setText("LABEL");
        classifiedLabelText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout analysisLayout = new javax.swing.GroupLayout(analysis);
        analysis.setLayout(analysisLayout);
        analysisLayout.setHorizontalGroup(
            analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analysisLayout.createSequentialGroup()
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(splitRatioTextField)
                            .addComponent(numPopulationTextField)
                            .addComponent(numIterationTextField)
                            .addComponent(c1TextField)
                            .addComponent(c2TextField)
                            .addComponent(targetTextField))
                        .addGap(1577, 1577, 1577))
                    .addGroup(analysisLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(analysisLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(analysisLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lantaiTextField)
                                            .addComponent(kelembabanTextField)
                                            .addComponent(pencahayaanTextField)
                                            .addComponent(ventilasiTextField)
                                            .addComponent(ptrTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(penghasilanTextField)
                                            .addComponent(pekerjaanTextField)
                                            .addComponent(pendidikanTextField)
                                            .addComponent(namaTextField)
                                            .addComponent(dindingTextField)
                                            .addComponent(atapTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analysisLayout.createSequentialGroup()
                                                .addComponent(classifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4))))
                                    .addGroup(analysisLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(classifiedLabelText)
                                        .addGap(82, 82, 82)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analysisLayout.createSequentialGroup()
                    .addContainerGap(322, Short.MAX_VALUE)
                    .addComponent(Hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1186, 1186, 1186)))
        );
        analysisLayout.setVerticalGroup(
            analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(splitRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPopulationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numIterationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analysisLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(hasilText))
                    .addGroup(analysisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pendidikanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pekerjaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penghasilanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ventilasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pencahayaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelembabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lantaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(4, 4, 4)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dindingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classifiedLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(analysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(analysisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Analysis", analysis);

        classification.setPreferredSize(new java.awt.Dimension(1874, 1000));

        jLabel38.setText("Nama");

        classifyButton1.setText("Proses");
        classifyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classifyButton1ActionPerformed(evt);
            }
        });

        classifiedLabelText1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        classifiedLabelText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classifiedLabelText1.setText("LABEL");
        classifiedLabelText1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        classifiedLabelText1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        classifiedLabelText1.setPreferredSize(new java.awt.Dimension(31, 16));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Pekerjaan");

        jLabel7.setText("Pendidikan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Penghasilan");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel49.setText("Ventilasi");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel50.setText("Kelembaban");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel51.setText("Lantai");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel52.setText("Atap");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel53.setText("PTR");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel54.setText("Pencahayaan");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel55.setText("Dinding");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout classificationLayout = new javax.swing.GroupLayout(classification);
        classification.setLayout(classificationLayout);
        classificationLayout.setHorizontalGroup(
            classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(hasilText1)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(classificationLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classifyButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaTextField1)
                    .addComponent(jComboBox8, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel54)
                    .addComponent(jComboBox9, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel51)
                    .addComponent(jComboBox6, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel52)
                    .addComponent(jComboBox7, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel49)
                    .addComponent(jComboBox4, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel50)
                    .addComponent(jComboBox5, 0, 214, Short.MAX_VALUE)
                    .addComponent(jLabel55)
                    .addComponent(jComboBox10, 0, 214, Short.MAX_VALUE)
                    .addComponent(classifiedLabelText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
        );
        classificationLayout.setVerticalGroup(
            classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationLayout.createSequentialGroup()
                .addGap(509, 509, 509)
                .addComponent(hasilText1)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(classificationLayout.createSequentialGroup()
                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classificationLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(classificationLayout.createSequentialGroup()
                                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(classificationLayout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(namaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(classificationLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(classificationLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(classificationLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(classificationLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(classificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(classificationLayout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(classifyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(classifiedLabelText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(318, 318, 318))
        );

        jTabbedPane1.addTab("Classification", classification);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setDataTable(List<entity.Data> data) {
        DefaultTableModel model = (DefaultTableModel)this
                                    .nutritionalStatusTable.getModel();
        model.setRowCount(0);
        model.setColumnCount(3 + entity.Data.FEATURES.length);
        Object[] obj;
        int i = 0;
        for (entity.Data row : data) {
            obj = new Object[model.getColumnCount()];
            obj[0] = ++i;
            obj[1] = row.getNama();
            for (int j = 0; j < entity.Data.FEATURES.length; j++) {
                obj[j + 2] = Reflector.callUserFunc(entity.Data.class, row, 
                        "get" + StringUtils
                                .capitalize(entity.Data.FEATURES[j]));
            }
            obj[2 + entity.Data.FEATURES.length] = Reflector.callUserFunc(
                entity.Data.class, row, "get" + StringUtils
                        .capitalize(entity.Data.LABEL));
            model.addRow(obj);
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void classifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classifyButtonActionPerformed
        // TODO add your handling code here:
        if (this.analyzed && this.trainedC45 != null &&
            this.trainedPSOC45 != null) {
            String nama = this.namaTextField.getText();
            int pendidikan = Integer.parseInt(this.pendidikanTextField
                .getText());
            int pekerjaan = Integer.parseInt(this.pekerjaanTextField.getText());
            int penghasilan = Integer.parseInt(this.penghasilanTextField
                .getText());
            int ptr = Integer.parseInt(this.ptrTextField.getText());
            int ventilasi = Integer.parseInt(this.ventilasiTextField.getText());
            int pencahayaan = Integer.parseInt(this.pencahayaanTextField.getText());
            int kelembaban = Integer.parseInt(this.kelembabanTextField.getText());
            int atap = Integer.parseInt(this.atapTextField.getText());
            int dinding = Integer.parseInt(this.dindingTextField.getText());
            int lantai = Integer.parseInt(this.lantaiTextField.getText());

            Data data = new Data(nama, pendidikan, pekerjaan, penghasilan, ptr,
                ventilasi, pencahayaan, kelembaban, atap, dinding, lantai);
            int predicted = this.trainedPSOC45.predictLabel(data);
            this.classifiedLabelText.setText("ISPA: " + predicted);

        } else {

        }
    }//GEN-LAST:event_classifyButtonActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        SplitValidator splitValidator =
        new SplitValidator((ArrayList)this.data);
        Map<String, List<entity.Data>> split = splitValidator
        .stratifiedSplit(Double
            .parseDouble(splitRatioTextField.getText()));
        List<entity.Data> trainData = split.get("train");
        List<entity.Data> testData = split.get("test");

        C45 clf = new C45();
        clf.fit(trainData);
        this.trainedC45 = clf;
        double c45Score = clf.score(testData);

        ConfusionMatrix cm = new ConfusionMatrix();
        for (entity.Data row : testData) {
            int predicted = clf.predictLabel(row);
            int actual = row.getIspa();
            cm.update(Integer.toString(actual), Integer.toString(predicted));
        }

        double c1 = Double.parseDouble(c1TextField.getText());
        double c2 = Double.parseDouble(c2TextField.getText());
        int numPopulation = Integer.parseInt(numPopulationTextField.getText());
        int numIteration = Integer.parseInt(numIterationTextField.getText());
        double target = Double.parseDouble(targetTextField.getText());

        PSO pso = new PSO(entity.Data.FEATURES.length, numPopulation,
            numIteration, c1, c2, target);
        Particle bestParticle = pso.exec(trainData, testData);
        double c45PsoScore = bestParticle.getBest();

        C45 optimizedClf = bestParticle.getClf();
        this.trainedPSOC45 = optimizedClf;
        ConfusionMatrix cmPso = new ConfusionMatrix();
        for (entity.Data row : testData) {
            int predicted = optimizedClf.predictLabel(row);
            int actual = row.getIspa();
            System.out.println(actual + "::" + predicted);
            cmPso.update(Integer.toString(actual), Integer.toString(predicted));
        }

        DefaultTableModel accuracyModel = (DefaultTableModel)this
        .accuracyTable.getModel();
        accuracyModel.setRowCount(1);
        accuracyModel.setColumnCount(2);
        accuracyModel.setValueAt((c45Score * 100) + "%", 0, 0);
        accuracyModel.setValueAt((c45PsoScore * 100) + "%", 0, 1);

        Map<String, Map<String, Integer>> c45Mat = cm.getMatrix();
        DefaultTableModel cmC45Model = (DefaultTableModel)this
        .cm_C45.getModel();
        cmC45Model.setRowCount(2);
        cmC45Model.setColumnCount(3);
        cmC45Model.setValueAt(c45Mat.get("1").get("1"), 0, 1);
        cmC45Model.setValueAt(c45Mat.get("1").get("2"), 0, 2);
        cmC45Model.setValueAt(c45Mat.get("2").get("1"), 1, 1);
        cmC45Model.setValueAt(c45Mat.get("2").get("2"), 1, 2);

        Map<String, Map<String, Integer>> psoC45Mat = cmPso.getMatrix();
        DefaultTableModel cmPsoC45Model = (DefaultTableModel)this
        .cm_PSOC45.getModel();
        cmPsoC45Model.setRowCount(2);
        cmPsoC45Model.setColumnCount(3);
        cmPsoC45Model.setValueAt(psoC45Mat.get("1").get("1"), 0, 1);
        cmPsoC45Model.setValueAt(psoC45Mat.get("1").get("2"), 0, 2);
        cmPsoC45Model.setValueAt(psoC45Mat.get("2").get("1"), 1, 1);
        cmPsoC45Model.setValueAt(psoC45Mat.get("2").get("2"), 1, 2);

        this.analyzed = true;
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void loadData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadData
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView()
            .getDefaultDirectory());
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = jfc.getSelectedFile();
                ExcelHandler handler = new ExcelHandler();
                this.data = handler.read(selectedFile, 1);
                this.setDataTable(this.data);
            } catch (IOException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loadData

    private void classifyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classifyButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classifyButton1ActionPerformed

    private void dev() {
//        ExcelHandler exl = new ExcelHandler();
//        List<Data> data;
//        try {
//            
//            data = exl.read("/data/data.xlsx", 1);
//            SplitValidator splitValidator = new SplitValidator(data);
//            Map<String, List<Data>> split = splitValidator
//                    .stratifiedSplit(SPLIT_RATIO);
//            List<Data> trainData = split.get("train");
//            List<Data> testData = split.get("test");
//
//            C45 clf = new C45();
//            clf.fit(trainData);
////            clf.showTree();
//            System.out.println(clf.score(testData));
//            
//            int[] params = new int[] {10, 20, 40, 80, 100};
//            
//            Map<Integer, Object[]> experimentData = new HashMap<>();
//            experimentData.put(0, new Object[] {"ID", "d", "NUM_POPULATION", 
//                                    "NUM_ITERATION", "C1", "C2", "SCORE", 
//                                    "d'", "SELECTED_FEATURES"});
//            int rownum = 1;
//            for (int population : params) {
//                for (int iteration : params) {
//                    double c1 = Math.random();
//                    double c2 = Math.random();
//                    PSO pso = new PSO(Data.FEATURES.length, population, 
//                                    iteration, c1, c2, 0.9);
//                    Particle bestParticle = pso.exec(trainData, testData);
//                    double score = bestParticle.getBest();
//                    System.out.println(c1 + ", " + c2 + ": " + score);
//
//                    List<String> selectedFeatures = bestParticle
//                            .getSelectedFeatures();
//                    experimentData.put(rownum, new Object[] {rownum++, 
//                        Data.FEATURES.length, population, iteration, 
//                        c1, c2, score, selectedFeatures.size(), 
//                        Arrays.toString(selectedFeatures
//                                .toArray(new String[0]))});
//                }
//            }
//            
//            exl.write("/data/test_result.xlsx", experimentData);
//        } catch (IOException ex) {
//            Logger.getLogger(C45PSO.class.getName()).log(Level.SEVERE, 
//                    null, ex);
//        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Hasil1;
    private javax.swing.JTable accuracyTable;
    private javax.swing.JPanel analysis;
    private javax.swing.JButton analyzeButton;
    private javax.swing.JTextField atapTextField;
    private javax.swing.JPanel buton_data;
    private javax.swing.JTextField c1TextField;
    private javax.swing.JTextField c2TextField;
    private javax.swing.JPanel classification;
    private javax.swing.JLabel classifiedLabelText;
    private javax.swing.JLabel classifiedLabelText1;
    private javax.swing.JButton classifyButton;
    private javax.swing.JButton classifyButton1;
    private javax.swing.JTable cm_C45;
    private javax.swing.JTable cm_PSOC45;
    private javax.swing.JPanel dashboard;
    private javax.swing.JTextField dindingTextField;
    private javax.swing.JLabel hasilText;
    private javax.swing.JLabel hasilText1;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kelembabanTextField;
    private javax.swing.JTextField lantaiTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField namaTextField1;
    private javax.swing.JTextField numIterationTextField;
    private javax.swing.JTextField numPopulationTextField;
    private javax.swing.JTable nutritionalStatusTable;
    private javax.swing.JTextField pekerjaanTextField;
    private javax.swing.JTextField pencahayaanTextField;
    private javax.swing.JTextField pendidikanTextField;
    private javax.swing.JTextField penghasilanTextField;
    private javax.swing.JTextField ptrTextField;
    private javax.swing.JTextField splitRatioTextField;
    private javax.swing.JPanel tabel_data;
    private javax.swing.JTextField targetTextField;
    private javax.swing.JPanel tittle_data;
    private javax.swing.JTextField ventilasiTextField;
    // End of variables declaration//GEN-END:variables
}
